/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio5jahaziel;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Jahaziel
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Casas = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        Nombre_casa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Seguridad_Casa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Direccion_casa = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        Canchas = new javax.swing.JDialog();
        Seguridad_canchas = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Direccion_canchas = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Nombre_Canchas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Estado_canchas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Categoria_cancha = new javax.swing.JComboBox<>();
        Restaurantes = new javax.swing.JDialog();
        Seguridad_Restaurante = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Direccion_Restaurante = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Nombre_Restaurante = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Categoria_Restaurante = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        Calificacion_Restaurante = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        MenuClickDerecho = new javax.swing.JPopupMenu();
        EliminarRes = new javax.swing.JMenuItem();
        eliminarcan = new javax.swing.JMenuItem();
        Eliminarcarr = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        TabCreacion = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        Numerocarretera = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Distancia = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Inicia = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        fin = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Tab_tree = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        Carreteras = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        J_tree = new javax.swing.JTree();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        J_list = new javax.swing.JList<>();
        jLabel21 = new javax.swing.JLabel();
        Cb = new javax.swing.JComboBox();

        jLabel2.setText("Nombre");

        jLabel3.setText("Direccion");

        jLabel4.setText("Nivel de seguridad");

        Direccion_casa.setColumns(20);
        Direccion_casa.setRows(5);
        jScrollPane1.setViewportView(Direccion_casa);

        jButton4.setText("Agregar Casa");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CasasLayout = new javax.swing.GroupLayout(Casas.getContentPane());
        Casas.getContentPane().setLayout(CasasLayout);
        CasasLayout.setHorizontalGroup(
            CasasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CasasLayout.createSequentialGroup()
                .addGroup(CasasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CasasLayout.createSequentialGroup()
                        .addGroup(CasasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CasasLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(61, 61, 61))
                            .addGroup(CasasLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(CasasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)))
                        .addGroup(CasasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre_casa, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Seguridad_Casa, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CasasLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton4)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        CasasLayout.setVerticalGroup(
            CasasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CasasLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(CasasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nombre_casa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CasasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(CasasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CasasLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4))
                    .addGroup(CasasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Seguridad_Casa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(35, 35, 35))
        );

        Direccion_canchas.setColumns(20);
        Direccion_canchas.setRows(5);
        jScrollPane2.setViewportView(Direccion_canchas);

        jButton5.setText("Agregar Cancha");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre");

        jLabel6.setText("Direccion");

        jLabel7.setText("Nivel de seguridad");

        jLabel8.setText("Estado ");

        jLabel9.setText("Categoria");

        Categoria_cancha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Football", "Basquet", "tennis", "Volley" }));

        javax.swing.GroupLayout CanchasLayout = new javax.swing.GroupLayout(Canchas.getContentPane());
        Canchas.getContentPane().setLayout(CanchasLayout);
        CanchasLayout.setHorizontalGroup(
            CanchasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CanchasLayout.createSequentialGroup()
                .addGroup(CanchasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CanchasLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(CanchasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CanchasLayout.createSequentialGroup()
                                .addGroup(CanchasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CanchasLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(61, 61, 61))
                                    .addGroup(CanchasLayout.createSequentialGroup()
                                        .addGroup(CanchasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(53, 53, 53)))
                                .addGroup(CanchasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nombre_Canchas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(CanchasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Categoria_cancha, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Estado_canchas, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Seguridad_canchas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))))
                            .addGroup(CanchasLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jButton5))))
                    .addGroup(CanchasLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        CanchasLayout.setVerticalGroup(
            CanchasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CanchasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(CanchasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Nombre_Canchas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CanchasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(CanchasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CanchasLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7))
                    .addGroup(CanchasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Seguridad_canchas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(CanchasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Estado_canchas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CanchasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(Categoria_cancha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(47, 47, 47))
        );

        Direccion_Restaurante.setColumns(20);
        Direccion_Restaurante.setRows(5);
        jScrollPane3.setViewportView(Direccion_Restaurante);

        jButton6.setText("Agregar restaurante");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel10.setText("Nombre");

        jLabel11.setText("Direccion");

        jLabel12.setText("Nivel de seguridad");

        jLabel13.setText("Categoria");

        Categoria_Restaurante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mexicano", "chino", "italiano", "comida rapida" }));

        jLabel14.setText("Calificacion");

        Calificacion_Restaurante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        javax.swing.GroupLayout RestaurantesLayout = new javax.swing.GroupLayout(Restaurantes.getContentPane());
        Restaurantes.getContentPane().setLayout(RestaurantesLayout);
        RestaurantesLayout.setHorizontalGroup(
            RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RestaurantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RestaurantesLayout.createSequentialGroup()
                        .addGroup(RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RestaurantesLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(61, 61, 61))
                            .addGroup(RestaurantesLayout.createSequentialGroup()
                                .addGroup(RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(RestaurantesLayout.createSequentialGroup()
                                        .addGroup(RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel13))
                                        .addGap(6, 6, 6)))
                                .addGap(53, 53, 53)))
                        .addGroup(RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Seguridad_Restaurante)
                            .addGroup(RestaurantesLayout.createSequentialGroup()
                                .addGroup(RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nombre_Restaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Calificacion_Restaurante, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Categoria_Restaurante, javax.swing.GroupLayout.Alignment.LEADING, 0, 101, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(RestaurantesLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton6)))
                .addGap(265, 265, 265))
        );
        RestaurantesLayout.setVerticalGroup(
            RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RestaurantesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Nombre_Restaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RestaurantesLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12))
                    .addGroup(RestaurantesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Seguridad_Restaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(Categoria_Restaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(Calificacion_Restaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(38, 38, 38))
        );

        EliminarRes.setText("Eliminar Restaurantes");
        EliminarRes.setToolTipText("");
        EliminarRes.setActionCommand("Eliminar ");
        EliminarRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarResActionPerformed(evt);
            }
        });
        MenuClickDerecho.add(EliminarRes);

        eliminarcan.setText("Eliminar canchas");
        eliminarcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarcanActionPerformed(evt);
            }
        });
        MenuClickDerecho.add(eliminarcan);

        Eliminarcarr.setText("eliminar Carretera");
        Eliminarcarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarcarrActionPerformed(evt);
            }
        });
        MenuClickDerecho.add(Eliminarcarr);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabCreacion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabCreacionStateChanged(evt);
            }
        });

        jButton1.setText("Canchas");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Casas");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Restaurantes");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel1.setText("¿Que desea Crear?");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabCreacion.addTab("Lugares", jPanel3);

        jLabel15.setText("Numero de carretera:");

        jLabel16.setText("Distancia");

        jLabel17.setText("KM");

        jLabel18.setText("Lugar donde inicia");

        Inicia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel19.setText("Lugar donde termina");

        fin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton7.setText("Agregar Carretera");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)))
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Numerocarretera)
                            .addComponent(Distancia)
                            .addComponent(Inicia, 0, 98, Short.MAX_VALUE)
                            .addComponent(fin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Numerocarretera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(Inicia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jButton7)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        TabCreacion.addTab("Carreteras", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabCreacion)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Creacion", jPanel1);

        Tab_tree.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Tab_treeStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Restaurantes");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Carreteras);
        Carreteras.setText("Carreteras");
        Carreteras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarreterasActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Canchas");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Tabla);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jRadioButton1)
                        .addGap(33, 33, 33)
                        .addComponent(Carreteras)
                        .addGap(29, 29, 29)
                        .addComponent(jRadioButton3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(Carreteras)
                    .addComponent(jRadioButton3))
                .addGap(73, 73, 73)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Tab_tree.addTab("Listar en table ", jPanel5);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Categorias");
        J_tree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane5.setViewportView(J_tree);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        Tab_tree.addTab("Listar en Jtree", jPanel6);

        J_list.setModel(new DefaultListModel()
        );
        jScrollPane7.setViewportView(J_list);

        jLabel21.setText("Lugar");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cb, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(Cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        Tab_tree.addTab("Listar en JList", jPanel7);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tab_tree, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tab_tree)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
         Tabla.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Direccion", "Nivel de seguridad", "Categoria", "Calificacion"
                }
        ));
        DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();

        for (int i = 0; i < restaurantes.size(); i++) {
            Object[] row = {
                restaurantes.get(i).getNombre(),
                restaurantes.get(i).getDireccion(),
                restaurantes.get(i).getN_seguridad(), 
                restaurantes.get(i).getCategoria(),
                restaurantes.get(i).getCalificacion()
            };
            modelo.addRow(row);
        }
        Tabla.setModel(modelo);

        
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        
        String direccion, nombre, estado, categoria ;
        int N_seguridad;
        
        nombre=this.Nombre_Canchas.getText();
        direccion=this.Direccion_canchas.getText();
        estado=this.Estado_canchas.getText();
        categoria=this.Categoria_cancha.getItemAt(Categoria_cancha.getSelectedIndex());
        N_seguridad=Integer.parseInt(this.Seguridad_canchas.getText());
        
        canchas.add(new Canchas(categoria, estado, nombre, direccion, N_seguridad));
        lugares.add(new Canchas(categoria, estado, nombre, direccion, N_seguridad));
        
       
        DefaultListModel modelo = (DefaultListModel) J_list.getModel();
        modelo.addElement(new Canchas(categoria, estado, nombre, direccion, N_seguridad)) ;
        J_list.setModel(modelo);
        
                DefaultTreeModel m = (DefaultTreeModel) J_tree.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
                DefaultMutableTreeNode tipo_categoria;
                tipo_categoria = nodo_cancha;
                DefaultMutableTreeNode nodo;
                nodo = new DefaultMutableTreeNode(Categoria_cancha.getSelectedItem().toString());
                DefaultMutableTreeNode nombre_can;
                nombre_can = new DefaultMutableTreeNode(Nombre_Canchas.getText());
                nodo.add(nombre_can);
                tipo_categoria.add(nodo);
                raiz.add(tipo_categoria);
                m.reload();

        
        Nombre_Canchas.setText("");
        Direccion_canchas.setText("");
        Estado_canchas.setText("");
        Categoria_cancha.setSelectedIndex(0);
        Seguridad_canchas.setText("");
        
        JOptionPane.showMessageDialog(null, "Ha sido agregado exitosamente!");
        
        
        
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        
        String direccion, nombre, categoria ;
        int N_seguridad, calificacion;
        
        nombre=this.Nombre_Restaurante.getText();
        direccion=this.Direccion_Restaurante.getText();
        categoria=this.Categoria_Restaurante.getItemAt(Categoria_Restaurante.getSelectedIndex());
        N_seguridad=Integer.parseInt(this.Seguridad_Restaurante.getText());
        calificacion =Integer.parseInt(this.Calificacion_Restaurante.getItemAt(Calificacion_Restaurante.getSelectedIndex()));
        
        restaurantes.add(new Restaurantes(categoria, calificacion, nombre, direccion, N_seguridad));
        lugares.add(new Restaurantes(categoria, calificacion, nombre, direccion, N_seguridad));
        
        DefaultListModel modelo = (DefaultListModel) J_list.getModel();
        modelo.addElement(new Restaurantes(categoria, calificacion, nombre, direccion, N_seguridad)) ;
        J_list.setModel(modelo);
        
                DefaultTreeModel m = (DefaultTreeModel) J_tree.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
                DefaultMutableTreeNode tipo_categoria;
                tipo_categoria = nodo_restaurante;
                DefaultMutableTreeNode nodo;
                nodo = new DefaultMutableTreeNode(Categoria_Restaurante.getSelectedItem().toString());
                DefaultMutableTreeNode nombre_can;
                nombre_can = new DefaultMutableTreeNode(Nombre_Restaurante.getText());
                nodo.add(nombre_can);
                tipo_categoria.add(nodo);
                raiz.add(tipo_categoria);
                m.reload();
                
         

        
        Nombre_Restaurante.setText("");
        Direccion_Restaurante.setText("");
        Categoria_Restaurante.setSelectedIndex(0);
        Seguridad_Restaurante.setText("");
        Calificacion_Restaurante.setSelectedIndex(0);
        
        JOptionPane.showMessageDialog(null, "Ha sido agregado exitosamente!");
        
        
        
        
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
         
        String direccion, nombre;
        int N_seguridad;
        
        nombre=this.Nombre_casa.getText();
        direccion=this.Direccion_casa.getText();
        N_seguridad=Integer.parseInt(this.Seguridad_Casa.getText());
        
        casas.add(new Casas(nombre, direccion, N_seguridad));
        lugares.add(new Casas(nombre, direccion, N_seguridad));
        
        
        
        Nombre_casa.setText("");
        Direccion_casa.setText("");
        Seguridad_Casa.setText("");
       
        JOptionPane.showMessageDialog(null, "Ha sido agregado exitosamente!");
       
        
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void CarreterasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarreterasActionPerformed
         Tabla.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Numero de carretera", "Distancia", "Lugar donde inicia", "Lugar donde terminar"
                }
        ));
        DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();

        for (int i = 0; i < carreteras.size(); i++) {
            Object[] row = {
                carreteras.get(i).getNumero_U(),
                carreteras.get(i).getDistancia(),
                carreteras.get(i).getInicio(),
                carreteras.get(i).getFin(),
            };
            modelo.addRow(row);
        }
        Tabla.setModel(modelo);
        
    }//GEN-LAST:event_CarreterasActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
          Tabla.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Direccion", "Nivel de seguridad", "Estado", "Categoria"
                }
        ));
        DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
        
        for (int i = 0; i < canchas.size(); i++) {
            Object[] row = {
                canchas.get(i).getNombre(),
                canchas.get(i).getDireccion(),
                canchas.get(i).getN_seguridad(),
                canchas.get(i).getEstado(),
                canchas.get(i).getCategoria()
            };
            modelo.addRow(row);
        }
        Tabla.setModel(modelo);
 
        
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        if (evt.isMetaDown()) {
            MenuClickDerecho.show(Tabla, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_TablaMouseClicked

    private void EliminarResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarResActionPerformed
        restaurantes.remove(Tabla.getSelectedRow());
        
        
        
    }//GEN-LAST:event_EliminarResActionPerformed

    private void Tab_treeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Tab_treeStateChanged
        
        
        if (Tab_tree.getSelectedIndex()==2){
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (int i = 0; i < lugares.size(); i++) {
                modelo.addElement(lugares.get(i));
            }
            Cb.setModel(modelo);
            
        }
        
        
        
    }//GEN-LAST:event_Tab_treeStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void eliminarcanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarcanActionPerformed
    canchas.remove(Tabla.getSelectedRow());
        
// TODO add your handling code here:
    }//GEN-LAST:event_eliminarcanActionPerformed

    private void EliminarcarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarcarrActionPerformed
      
        carreteras.remove(Tabla.getSelectedRow());
    }//GEN-LAST:event_EliminarcarrActionPerformed

    private void TabCreacionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabCreacionStateChanged
        if (TabCreacion.getSelectedIndex() == 1) {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (int i = 0; i < lugares.size(); i++) {
                modelo.addElement(lugares.get(i));
            }
            Inicia.setModel(modelo);
        }

        if (TabCreacion.getSelectedIndex() == 1) {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (int i = 0; i < lugares.size(); i++) {
                modelo.addElement(lugares.get(i));
            }
            fin.setModel(modelo);
        }

        
    }//GEN-LAST:event_TabCreacionStateChanged

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked

        int NumeroCarretera, Distancia;
        Lugares inicio, fin;

        NumeroCarretera=Integer.parseInt(this.Numerocarretera.getText());
        Distancia =Integer.parseInt(this.Distancia.getText());
        inicio = (Lugares)this.Inicia.getItemAt(Inicia.getSelectedIndex());
        fin = (Lugares)this.fin.getItemAt(this.fin.getSelectedIndex());
        inicio.setEntrada(new Carreteras(NumeroCarretera, Distancia, inicio, fin));
        fin.setEntrada(new Carreteras(NumeroCarretera, Distancia, inicio, fin));
        carreteras.add(new Carreteras(NumeroCarretera, Distancia, inicio, fin));
        DefaultListModel modelo = (DefaultListModel) J_list.getModel();
        modelo.addElement( new Carreteras(NumeroCarretera, Distancia, inicio, fin)) ;
        J_list.setModel(modelo);

        Numerocarretera.setText("");
        this.Distancia.setText("");
        Inicia.setSelectedIndex(0);
        this.fin.setSelectedIndex(0);

        JOptionPane.showMessageDialog(null, "Ha sido agregado exitosamente!");
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Restaurantes.setModal(true);
        Restaurantes.pack();
        Restaurantes.setLocationRelativeTo(this);
        Restaurantes.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Casas.setModal(true);
        Casas.pack();
        Casas.setLocationRelativeTo(this);
        Casas.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Canchas.setModal(true);
        Canchas.pack();
        Canchas.setLocationRelativeTo(this);
        Canchas.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Calificacion_Restaurante;
    private javax.swing.JDialog Canchas;
    private javax.swing.JRadioButton Carreteras;
    private javax.swing.JDialog Casas;
    private javax.swing.JComboBox<String> Categoria_Restaurante;
    private javax.swing.JComboBox<String> Categoria_cancha;
    private javax.swing.JComboBox Cb;
    private javax.swing.JTextArea Direccion_Restaurante;
    private javax.swing.JTextArea Direccion_canchas;
    private javax.swing.JTextArea Direccion_casa;
    private javax.swing.JTextField Distancia;
    private javax.swing.JMenuItem EliminarRes;
    private javax.swing.JMenuItem Eliminarcarr;
    private javax.swing.JTextField Estado_canchas;
    private javax.swing.JComboBox Inicia;
    private javax.swing.JList<String> J_list;
    private javax.swing.JTree J_tree;
    private javax.swing.JPopupMenu MenuClickDerecho;
    private javax.swing.JTextField Nombre_Canchas;
    private javax.swing.JTextField Nombre_Restaurante;
    private javax.swing.JTextField Nombre_casa;
    private javax.swing.JTextField Numerocarretera;
    private javax.swing.JDialog Restaurantes;
    private javax.swing.JTextField Seguridad_Casa;
    private javax.swing.JTextField Seguridad_Restaurante;
    private javax.swing.JTextField Seguridad_canchas;
    private javax.swing.JTabbedPane TabCreacion;
    private javax.swing.JTabbedPane Tab_tree;
    private javax.swing.JTable Tabla;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem eliminarcan;
    private javax.swing.JComboBox fin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    
    ArrayList <Carreteras> carreteras = new ArrayList();
    ArrayList <Lugares> lugares = new ArrayList();
    ArrayList <Canchas> canchas = new ArrayList();
    ArrayList <Casas> casas = new ArrayList();
    ArrayList <Restaurantes> restaurantes = new ArrayList();
    
    DefaultMutableTreeNode nodo_restaurante = new DefaultMutableTreeNode("Restaurante");
    DefaultMutableTreeNode nodo_cancha = new DefaultMutableTreeNode("Cancha");
    Lugares lugar_seleccionado;
    
        
// porque tantos commits :( XD
   //jasbdjhabdjwahjawhbdawbdawjhdbwajdbwajhwajbda
//Holis 
}
